spring:
  application:
    name: driver-tracking
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: none
  config:
    import: optional:file:env.properties
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 9090

api:
  version: v1
  base-version: v0

jwt:
  secret: ${JWT_SECRET_KEY}

app:
  file:
    upload-dir: uploads          # relative to working dir

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

resilience4j.ratelimiter:
  instances:
    apiRateLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0












